- hosts: kubernetes
  user: root

  tasks:
    - name: deploy myapp on kubernetes
      command: kubectl apply -f myapp-deployment.yml

    - name: create service for myapp
      command: kubectl apply -f myapp-service.yml

    - name: update deployment with new pods if image updated in docker hub
      command: kubectl rollout restart deployment.apps/prats-myapp
